### ISSUE TITLE
C# Programming File Does Not Open

### ISSUE THREAD

**Issue by muhammadbaneshi** [dibagaran/cs-2015-7-alpha#1]
C# Programming File Does Not Open
It Is Ruin

**Comment by elahe-asadollahi** [comment]
C# programming pdf file is opening.....not have problem
chang ur browser....plz

**Comment by meysam-mousavi** [comment]
I just double checked it and works fine.
Cheers

**Comment by muhammadbaneshi** [comment]
Thanks it's okay

**Comment by SamiraSoltani** [comment]
how can i fix this error?
![error](https://cloud.githubusercontent.com/assets/13216906/8903186/4377b252-346b-11e5-8e07-c81abb56634d.PNG)
