### ISSUE TITLE
make simple menu with object programming

### ISSUE THREAD

**Issue by mohsen-alighanbari** [dibagaran/cs-2015-7-alpha#3]
Dear professor Mosavi
I want to create multiple menu with swap color method in it in one of the class program Home-works. however the code have not been work till now. it shows the menu however the swap color method doesn't have proper function. I was separate one the simple menus form the rest of the program and set it on the new solution. But the result were appeared to be the same. 
The Code were correct in accordance to the compiler.
the separated code were given below.
If you need the full code or the visual basic source code , please inform me which I will send it to you as fast as possible.
yours truly
Alighanbari.

// THE CLASS CODE 

class Class1
    {
        private string[] Language = { "English", "Persian", "French", "Exit" };
        private int choice = -1;
        public void ShowMenuAndRun()
        {
            while (true)
            {
                LanguageMenu(Language, choice);
                switch (Console.ReadKey(true).Key)
                {
                    case ConsoleKey.RightArrow:
                        choice = choice == Language.Length - 1 ? 0 : choice + 1;
                        break;
                    case ConsoleKey.LeftArrow:
                        choice = choice == 0 ? Language.Length - 1 : choice - 1;
                        break;
                }
            }
        }

// swap color codes
         private void SwapColor()
        {
            ConsoleColor OldForgroung = Console.BackgroundColor;
            ConsoleColor OldBackgroung = Console.ForegroundColor;
            Console.ForegroundColor = OldBackgroung;
            Console.BackgroundColor = OldForgroung;
        }

// shows the menu
         private void LanguageMenu(string[] Language, int choice)
        {
            Console.CursorVisible = false;
            Console.Clear();
            for (int i = 0; i < Language.Length; i++)
            {
                if (i == choice)
                {
                    SwapColor();
                    Console.Write(" " + Language[i] + " ");
                    SwapColor();
                }
                else
                {
                    Console.Write(" " + Language[i] + " ");
                }
            }
        }
    }

// MAIN BLOCK

static void Main(string[] args)
        {
            new Class1().ShowMenuAndRun();
        }

**Comment by AMINEDGE** [comment]
Dude if you look at your SwapColor Method you've written like this

oldBackground = Console.ForegroundColor;
oldForeground = Console.BackgroundColor;

You see it's not correct because you gave oldBackground your current ForegroundColor and gave oldForeground current BackgroundColor but you should give oldBackground current BackgroundColor and give oldForeground current ForegroundColor so you have to write like this

oldForeground = Console.ForegroundColor;
oldBackground = Console.BackgroundColor;
Console.ForegroundColor = oldBackground;
Console.BackgroundColor = oldForeground;

Then it should work now!
Best Regards

**Comment by mohsen-alighanbari** [comment]
Dear AMINEDGE
I perform the change you had mentioned above and the program worked as it should be. thanks for your help and consideration.

sincerely yours
Alighanbari
